// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmINiQ-ZmFJAtW1bB3Mxf1PB1D2ypii6k',
    appId: '1:211484229327:web:75e16e10690687f4f201ba',
    messagingSenderId: '211484229327',
    projectId: 'image-5c6df',
    authDomain: 'image-5c6df.firebaseapp.com',
    storageBucket: 'image-5c6df.appspot.com',
    measurementId: 'G-MR8FKJXN8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXErOH1OJG9sALACatzD38sA4w5YalIqM',
    appId: '1:211484229327:android:1d32329bf13e4b5bf201ba',
    messagingSenderId: '211484229327',
    projectId: 'image-5c6df',
    storageBucket: 'image-5c6df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1X9DeCm5Jgao-beGrZJ5gyT5qsD7rCA',
    appId: '1:211484229327:ios:91946f60790896d7f201ba',
    messagingSenderId: '211484229327',
    projectId: 'image-5c6df',
    storageBucket: 'image-5c6df.appspot.com',
    iosBundleId: 'com.example.insurenceTransmaa2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1X9DeCm5Jgao-beGrZJ5gyT5qsD7rCA',
    appId: '1:211484229327:ios:b90362d78cb203b8f201ba',
    messagingSenderId: '211484229327',
    projectId: 'image-5c6df',
    storageBucket: 'image-5c6df.appspot.com',
    iosBundleId: 'com.example.insurenceTransmaa2.RunnerTests',
  );
}
